### ISSUE TITLE
fasta file error

### ISSUE THREAD

**Issue by xiekunwhy** [ishinder/EASTR#18]
Hi,

I run eastr using following command, I got some error, told me that rbu.fa is not fasta file, but it is a fasta file,
```
cd /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/03.mapping/stem;source /Bio/User/kxie/software/miniforge3/bin/activate /Bio/User/kxie/software/miniforge3/envs/eastr;/Bio/User/kxie/software/miniforge3/envs/eastr/bin/eastr --bam /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/03.mapping/flower.sort.bam --reference /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/01.ref/bowtie2/rbu.fa --bowtie2_index /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/01.ref/bowtie2/rbu.fa --out_filtered_bam /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/03.mapping/stem/stem -p 10
```

the error
```
[fai_fetch] Warning - Reference -r not found in FASTA file, returning empty sequence
[fai_fetch] Warning - Reference /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/03.mapping/stem/tmpciy_v6hi not found in FASTA file, returning empty sequence
[fai_fetch] Warning - Reference -o not found in FASTA file, returning empty sequence
[fai_fetch] Warning - Reference /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/03.mapping/stem/tmpintcv2e_ not found in FASTA file, returning empty sequence
Traceback (most recent call last):
  File "/Bio/User/kxie/software/miniforge3/envs/eastr/bin/eastr", line 8, in <module>
    sys.exit(main())
  File "/Bio/User/kxie/software/miniforge3/envs/eastr/lib/python3.10/site-packages/EASTR/run_eastr.py", line 257, in main
    spurious_dict = get_spurious_introns.get_spurious_junctions(scoring, k, w, m, overhang, min_duplicate_exon_length, bt2_index, bt2_k,
  File "/Bio/User/kxie/software/miniforge3/envs/eastr/lib/python3.10/site-packages/EASTR/get_spurious_introns.py", line 239, in get_spurious_junctions
    self_introns = get_self_aligned_introns(introns, seqs, overhang, k, w, m, scoring)
  File "/Bio/User/kxie/software/miniforge3/envs/eastr/lib/python3.10/site-packages/EASTR/get_spurious_introns.py", line 16, in get_self_aligned_introns
    rseq = seqs[introns[key]['jstart']]
KeyError: 'Hap1_chr1:9588-9687'

```

Best,
Kun

**Comment by ishinder** [comment]
Hi Kun,

Thank you for reporting this issue.

Please check whether there is a mismatch between the scaffold names in the FASTA file and the scaffold names in the BAM file. This mismatch may be leading to the error you are encountering. Here are some commands you can use to check for this:

1. Extract scaffold names from the FASTA file:
`grep '>' /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/01.ref/bowtie2/rbu.fa | sed 's/>//' | sort > fasta_scaffolds.txt`

2. Extract scaffold names from the BAM file:
`samtools idxstats /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/03.mapping/flower.sort.bam | cut -f 1 | sort > bam_scaffolds.txt`

3. Compare the scaffold names:
`diff fasta_scaffolds.txt bam_scaffolds.txt`

Additionally, in your EASTR command, it appears that the Bowtie2 index is specified as a FASTA file, which is not correct. The Bowtie2 index should be generated separately from the FASTA file. The instructions for making a Bowtie2 index can be found here: [Bowtie2 Manual - Indexing a Reference Genome](https://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#indexing-a-reference-genome).

-Ida

**Comment by xiekunwhy** [comment]
Hi @ishinder ,

Thank you for your reply, here is the first command line results,
```
grep '>' /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/01.ref/bowtie2/rbu.fa | sed 's/>//' | sort
Hap1_chr1
Hap1_chr2
Hap1_chr3
Hap1_chr4
Hap1_chr5
```

and here is the second command line results,
```
samtools idxstats /state/partition1/WORK/Bio/Project/xiek/pipe/geneAnnot/Rbu/pipe/02.mrna/03.mapping/flower.sort.bam | cut -f 1 | sort
*
Hap1_chr1
Hap1_chr2
Hap1_chr3
Hap1_chr4
Hap1_chr5
```
and here is the third command line results,
```
diff fasta_scaffolds.txt bam_scaffolds.txt
0a1
> *
```

the star (*) is unmmap reads, so I don't think this error took place because of fasta header do not match is fasta and bam files.

rbu.fa is not only the references fasta, but also the bowtie2 index prefix, because I build the index using following command,
```
bowtie2-build --threads 10 rbu.fa rbu.fa
```
Best,
Kun

**Comment by xiekunwhy** [comment]
I think I know why, just because rbu.fa is a soft-link file, eastr pipeline run normally when I change soft-link to hard-link (just cp instead of ln -s), so I think it is a bug when reading soft-link references fasta.

**Comment by ishinder** [comment]
I'm glad this issue is resolved.

EASTR also requires the FASTA file to be indexed. The issue is likely that you soft-linked just the FASTA file without the accompanying *.fai index. Thank you for pointing this out to us. We will add a print statement to EASTR to catch such issues in the future.

**Comment by ishinder** [comment]
To prevent similar issues in the future, add a print statement to EASTR to notify users when the FASTA index file is missing.
